- src/Directory.Build.props
- src/Dotnet.ProjInfo/Dotnet.ProjInfo.fsproj
- src/Dotnet.ProjInfo/ExternalFSharp/FscConfig.fs
- src/Dotnet.ProjInfo/NETFrameworkInfoFromMSBuild.fs
- src/Dotnet.ProjInfo/Resources.fs
- src/Dotnet.ProjInfo/Resources/EnvironmentInfo.proj
- src/dotnet-proj-info/Inspect.fs
- src/dotnet-proj-info/Program.fs
this add
cli arg `--net-fw-references-path`, used as `--net-fw-references-path System System.Data`
This support also `-f` (`--framework`) argument, like `-f v4.7`. Note that the value is the target framework versio (`TargetFrameworkVersion` msbuild prop)
cli arg `--installed-net-frameworks`
list of the installed .NET Frameworks versions
now show the project refs
> add gather info about installed .net framework

- .travis.yml
- build.proj
- src/Dotnet.ProjInfo/NETFrameworkInfoFromMSBuild.fs
- src/dotnet-proj-info.sln
- src/dotnet-proj-info/Inspect.fs
- src/dotnet-proj-info/Program.fs
- test/dotnet-proj-info.Tests/FileUtils.fs
- test/dotnet-proj-info.Tests/Program.fs
- test/dotnet-proj-info.Tests/Sample.fs
- test/examples/sample1-oldsdk-lib/l1/l1.fsproj
- add test `--installed-net-frameworks`
- add test `--net-fw-references-path`
- use env var `DOTNET_PROJ_INFO_MSBUILD_BL` to generate msbuild binary log
- add hack to disable `FrameworkPathOverride` env var when running `msbuild`. That env var it's a workaround for building `net` tfm with .net core sdk on unix.
- unset env var `MSBuildExtensionsPath`, to fix running `msbuild` on travis otherwise the sdk is overriden with the one in .net core sdk
> add more tests

- src/dotnet-proj-info/Program.fs
- test/dotnet-proj-info.Tests/Program.fs
- test/dotnet-proj-info.Tests/Sample.fs
Use sub commands in cli
```
proj-info.
USAGE: proj-info [--help] [--verbose] [<subcommand> [<options>]]
SUBCOMMANDS:
get <options>         get project info
net-fw <options>      .NET Framework info
Use 'proj-info <subcommand> --help' for additional information.
OPTIONS:
--verbose, -v         verbose log
--help                display this list of options.
```
and
```
proj-info.
USAGE: proj-info get [--help] [--fsc-args] [--csc-args] [--project-refs] [--property [<string>...]]
[--framework <string>] [--runtime <string>] [--configuration <string>] [--msbuild <string>]
[--dotnetcli <string>] [--msbuild-host <auto|msbuild|dotnetmsbuild>] [<string>]
PROJECT:
<string>              the MSBuild project file
OPTIONS:
--fsc-args            get fsc arguments
--csc-args            get csc arguments …
```
> change cli, use sub commands

- build.proj
- src/dotnet-proj-info/Program.fs
- test/dotnet-proj-info.Tests/Sample.fs
split `get` subcommand in multiple subcommands
- `prop`
- `fsc-args`
- `csc-args`
- `p2p`
extract from `net-fw` the `net-fw-ref` commands
> extract multiple subcmds

- src/dotnet-proj/Inspect.fs
- src/dotnet-proj/Program.fs
- test/dotnet-proj.Tests/Sample.fs
fix #10
use `CustomAfterMicrosoftCommonTargets` property as hook instead of a custom target file in `obj` dir, who has issues with incremental rebuild
remove the deprecated target, if found because was in `obj` dir from a previous run
> use CustomAfterMicrosoftCommonTargets property as hook

- Directory.Build.props
- src/Dotnet.ProjInfo/Inspect.fs
- src/Dotnet.ProjInfo/NETFrameworkInfoFromMSBuild.fs
remove usage of `Choice`, use `Result` instead
bump version to v0.31
> normalize api, use `Result` in all target frameworks

- src/Dotnet.ProjInfo.Workspace.FCS/Library.fs
- test/Dotnet.ProjInfo.Workspace.FCS.Tests/Tests.fs
> the FSharpProjectOptions.ProjectId is always None

- src/Dotnet.ProjInfo.Workspace.FCS/Library.fs
- src/Dotnet.ProjInfo.Workspace/ProjectCrackerDotnetSdk.fs
- src/Dotnet.ProjInfo.Workspace/ProjectCrackerTypes.fs
- test/Dotnet.ProjInfo.Workspace.FCS.Tests/Program.fs
- test/Dotnet.ProjInfo.Workspace.FCS.Tests/Tests.fs
- test/Dotnet.ProjInfo.Workspace.Tests/Tests.fs
- test/dotnet-proj.Tests/TestAssets.fs
- test/examples/sample7-oldsdk-projs/README.md
- test/examples/sample7-oldsdk-projs/a/Project1A.fs
- test/examples/sample7-oldsdk-projs/a/Project1A.fsproj
- test/examples/sample7-oldsdk-projs/b/Project1B.fs
- test/examples/sample7-oldsdk-projs/b/Project1B.fsproj
- test/examples/sample7-oldsdk-projs/m1/MultiProject1.fs
- test/examples/sample7-oldsdk-projs/m1/MultiProject1.fsproj
fix FCS ProjectOptions of projects with project references
The FCS `ReferencedProjects` key is the project `TargetPath` property (the path of output assembly in `bin`, not `obj`)
> fix FCS ProjectOptions of projects with project references

- .vscode/launch.json
- .vscode/tasks.json
- Directory.Build.props
- src/Dotnet.ProjInfo.Workspace/Library.fs
- src/Dotnet.ProjInfo.Workspace/ProjectCrackerDotnetSdk.fs
- src/Dotnet.ProjInfo.Workspace/ProjectCrackerTypes.fs
- test/Dotnet.ProjInfo.Workspace.Tests/Tests.fs
use `ProjectViewer.Render` to get shown source files
> add ProjectViewer

- .gitignore
- .vscode/launch.json
- src/Dotnet.ProjInfo.Workspace/Dotnet.ProjInfo.Workspace.fsproj
- src/Dotnet.ProjInfo.Workspace/Library.fs
- src/Dotnet.ProjInfo.Workspace/ProjectCrackerDotnetSdk.fs
- src/Dotnet.ProjInfo.Workspace/ProjectCrackerTypes.fs
- src/Dotnet.ProjInfo.Workspace/VisualTree.fs
- src/Dotnet.ProjInfo/Inspect.fs
- src/dotnet-proj/Program.fs
- test/Dotnet.ProjInfo.Workspace.Tests/Tests.fs
- test/dotnet-proj.Tests/TestAssets.fs
- test/examples/sample8-netsdk-explorer/README.md
- test/examples/sample8-netsdk-explorer/n1/LibraryA.fs
- test/examples/sample8-netsdk-explorer/n1/LibraryB.fs
- test/examples/sample8-netsdk-explorer/n1/LibraryC.fs
- test/examples/sample8-netsdk-explorer/n1/n1.fsproj
- add `dotnet proj item` command 
- add `Inspect.getItems` to get msbuild items
- support multiple metadata and items in same query
- support depends on targets, to hook at different positions
- each item return as additional info the expected virtual path for visualization
- same VS behaviour for compile file outside fsproj directory (not in subdirectory). The virtual path will show only the file name.
- virtual paths use `/` as dir separator
- support `Link` metadata
fix #53
> support get items

- src/Dotnet.ProjInfo.Workspace/ProjectCrackerDotnetSdk.fs
for get_items target some projects return skipped, others ok.
It doesnt matter, that info is unused to get crosstargeting tfms
fix https://github.com/enricosada/dotnet-proj-info/issues/59
> fix crosstargeting

- src/dotnet-proj/runtimeconfig.template.json
Right now, dotnet-proj doesn't run on .net core 3 runtimes because it's not built for that yet.  This MR provides a runtimeconfig template file that's used by the build to set the roll-forward policy for the application, so now it work on the next-major-version as well, so any 3.x runtime.  This is intended to be a temporary measure until the project can be properly cross-targeted on release.
> add rollforward config to allow for netcore3 running

- src/Dotnet.ProjInfo.Workspace.FCS/Library.fs
- src/Dotnet.ProjInfo.Workspace/Binder.fs
- src/Dotnet.ProjInfo.Workspace/Dotnet.ProjInfo.Workspace.fsproj
- src/Dotnet.ProjInfo.Workspace/ProjectCrackerTypes.fs
allow to use `DPI.Workspace.FCSAdapter` like `DPI.Workspace.FCS.FCSBinder`, without reference FCS package
users of `DPI.Workspace.FCSAdapter` need to provider a mapper function `FCSProjectOptionsData -> FCS.FSharpProjectOptions`, but the two types are structural equivalent so is simple
> move fcs binder in DPI.Workspace

- src/Dotnet.ProjInfo.Workspace/Library.fs
- src/Dotnet.ProjInfo.Workspace/NETFrameworkInfoProvider.fs
- src/Dotnet.ProjInfo.Workspace/ProjectCrackerTypes.fs
- src/Dotnet.ProjInfo/Inspect.fs
- src/dotnet-proj/Program.fs
- src/dotnet-proj/dotnet-proj.fsproj
- test/Dotnet.ProjInfo.Workspace.Tests/Tests.fs
support dirname as input instead of full proj path
restore before execute commands (if .net sdk project)
refactor code to cleanup, remove unused ifdef
> support dirname as tool input, restore before execute commands

- Directory.Build.props
On Nuget https://www.nuget.org/packages/Dotnet.ProjInfo/
the Project Site leads to an 404
the License info to a fork (of @enricosada)
and the repo URL is also not found.
I assume every link should go here as IonideProject was renamed to ionide only.
> fix github url

- src/Dotnet.ProjInfo.Workspace/InspectSln.fs
- src/Dotnet.ProjInfo.Workspace/Library.fs
- src/Dotnet.ProjInfo/Inspect.fs
- test/Dotnet.ProjInfo.Workspace.Tests/Tests.fs
Two things
1. Expose the solution file cracking API and project file load order (without a full call to LoadSln)
2. Fix the acquisition of a temp file with a suffix, per https://stackoverflow.com/questions/581570/how-can-i-create-a-temp-file-with-a-specific-extension-with-net.  The current approach wasn't always working in multi-threaded execution, with different paths returning the same temp file name
> Provide solution project file order API

- src/Dotnet.ProjInfo.Workspace/ProjectCrackerTypes.fs
There is an argument for embeding files in the .pdb files and there are some project files which get AssemblyInfo files wrapped in this argument like this `--embed:obj\...AssemblyInfo.fs`. 
The AssemblyInfo file is once more listed as a normal source file arg.
The function isCompileFile checked only the extension at the end and assigned this arg to source files. Later the file is converted tu full path and access to it throws exception.
There was also a TODO comment with excatly this statement so I removed it after fixing this.
> fix invalid handling of --embed and other arguments

- src/Directory.Build.props
- src/Ionide.ProjInfo.FCS/paket.references
- src/Ionide.ProjInfo.ProjectSystem/paket.references
- src/Ionide.ProjInfo.Sln/FileUtilities.cs
- src/Ionide.ProjInfo.Sln/Ionide.ProjInfo.Sln.csproj
- src/Ionide.ProjInfo/paket.references
This sets a few properties for all the published projects so that sourcelink works. The core issue was that the pdbs weren't included in the package (and they contain the sourcelink information), but I sidestepped this by embedding them in the DLL. Much simpler that way.
After this change, if you run `sourcelink test <path to generated nuget>.nupkg` for any of the nuget packages in this project, the sourcelink tests will pass.
> Set properties such that pdbs are embedded in the dll and sourcelink tests pass

- CHANGELOG.md
- build.fsx
- src/Ionide.ProjInfo/Library.fs
- src/Ionide.ProjInfo/Utils.fs
The F# targets for several versions have set some properties based on the presence of the DOTNET_HOST_PATH environment variable, which the dotnet CLI sets when `dotnet build` or `dotnet msbuild` are run.  In 5.0.200 and up, some internal default values for these properties changed that resulted in failed cracking in this library due to invalid values, which brought to light that we were never setting this environment variable. As soon as we do (using the algorithm from the dotnet CLI itself to discover the path), all of the cracking issues go away.
>  Fix .net sdk 5.0.200 and up cracking error

- src/Ionide.ProjInfo.ProjectSystem/ProjectSystem.fs
- src/Ionide.ProjInfo/Library.fs
In https://github.com/ionide/proj-info/pull/101/files\#r588779221 I said I didn't see a reason to exit early.  Well turns of FSAC relies on this behavior.  This backs out that change and puts checks around reloads instead. Also I clean up some variable names I forgot to finish out on another PR.
> Fixing fsac stalls

- CHANGELOG.md
- src/Ionide.ProjInfo/Library.fs
- test/Ionide.ProjInfo.Tests/Tests.fs
- test/examples/sample2-netsdk-lib/n1/n1.fsproj
> Allow global properties to be provided to project loaders

- src/Ionide.ProjInfo.Tool/Ionide.ProjInfo.Tool.fsproj
- src/Ionide.ProjInfo.Tool/Program.fs
- src/Ionide.ProjInfo/Library.fs
- src/Ionide.ProjInfo/Utils.fs
- test/Ionide.ProjInfo.Tests/Tests.fs
This should fix #123 by
* probing additional discovery mechanisms
* failing fast on the `init` call and notifying the caller what they need to do in order to become compliant.
I thought about making this return a result, but this is kinda a catastrophic failure mode - if we can't find the dotnet binary then nothing else works, either.
> Add additional fallback probes

- src/Ionide.ProjInfo/Library.fs
- src/Ionide.ProjInfo/Utils.fs
This is a promising approach, though if the props in [the compiler](https://github.com/dotnet/fsharp/blob/eccf87b7c8ea1a62dbb9481f12c5ba02ca80b8e6/src/fsharp/FSharp.Build/Microsoft.FSharp.NetSdk.props#L59-L67) change we might be broken.
> set some F#-specific parameters that are used in lieu of setting DOTNET_HOST_PATH

- src/Ionide.ProjInfo.ProjectSystem/Project.fs
- src/Ionide.ProjInfo.ProjectSystem/WorkspacePeek.fs
- src/Ionide.ProjInfo.Sln/FileUtilities.cs
- src/Ionide.ProjInfo.Sln/Ionide.ProjInfo.Sln.csproj
- src/Ionide.ProjInfo.Sln/NativeMethods.cs
- src/Ionide.ProjInfo.Sln/vendor/Constants.cs
- src/Ionide.ProjInfo.Sln/vendor/ProjectConfigurationInSolution.cs
- src/Ionide.ProjInfo.Sln/vendor/ProjectInSolution.cs
- src/Ionide.ProjInfo.Sln/vendor/SolutionConfigurationInSolution.cs
- src/Ionide.ProjInfo.Sln/vendor/SolutionFile.cs
- src/Ionide.ProjInfo/InspectSln.fs
This updates the vendored msbuild libraries and removes some unused shims, keeping the solution files support that doesn't exist upstream.
> update vendored MSBuild libs and expose wrappers for .slnf files

- test/Ionide.ProjInfo.Tests/Tests.fs
Starts to address https://github.com/ionide/proj-info/issues/122 (as part of finishing https://github.com/fsprojects/FSharp.Formatting/pull/719)
I'm not actually 100% sure what the problem was that https://github.com/fsprojects/FSharp.Formatting/pull/719 was hitting and it may have already been addressed by updates .  But either way we will need a test case for getProjectInfo that we can expand out later as we work out the corner case we were hitting
> add test case for getProjectInfo

- src/Ionide.ProjInfo.FCS/Library.fs
- test/Ionide.ProjInfo.Tests/Tests.fs
I think csproj and vbproj can be added as FSharpReference if the binary exists.
> Add C# projects as reference if the targetPath is present.

- src/Ionide.ProjInfo/Library.fs
I'm currently tinkering with a large solution (300+ projects) and this bit wasn't resolving for me.
@TheAngryByrd I believe this yields the same result, what do you think?
> Simplify getting the build projects from the GraphBuildResult.

- src/Ionide.ProjInfo.FCS/Library.fs
- test/Ionide.ProjInfo.Tests/Tests.fs
- test/examples/sample-referenced-csharp-project/csharp-lib/Class1.cs
- test/examples/sample-referenced-csharp-project/csharp-lib/csharp-lib.csproj
- test/examples/sample-referenced-csharp-project/fsharp-exe/Program.fs
- test/examples/sample-referenced-csharp-project/fsharp-exe/fsharp-exe.fsproj
We should provide file timestamps and file content streams for PE references so that the compiler doesn't get _too_ hungry
> use correct timestamp and file stream for cross-language references

- README.md
Old link was pointing to an old version of the file from before the `master -> main` rename.
> README.md: Fix link to Contributing.md

- test/Ionide.ProjInfo.Tests/Tests.fs
...as a proxy for checking that every project is mapped once and cached.
Test creates a "dense" graph:
- 4 layers, 2 projects in each layer
- Projects in each layer reference both projects from the previous layer
It then calls `mapManyOptions` and asserts that the returned graph of `FSharpProjectOptions` contains no duplicates ie. objects are reused.
When I removed the caching on the branch, the result was:
```
[23:12:19 ERR] Main tests.When creating FCS options, caches them failed in 00:00:07.4900000.
Mapping should reuse instances of FSharpProjectOptions and only create one per project.
expected: 8
actual: 52
...
Failed:   1
Main tests.When creating FCS options, caches them
Errored:  0 <Expecto>
```
When caching is enabled, test passes:
```
Failed:   0
Errored:  0 <Expecto>
```
> Add a unit test that checks that the returned FSharpProjectOptions graph doesn't contain duplicates

- src/Ionide.ProjInfo.FCS/Library.fs
- test/Ionide.ProjInfo.Tests/Tests.fs
Closes #155 by providing an all-in-one mapping function in addition to the one-shot mapping function. Would like to grab some of the dense tests from dotnet/fsharp to verify before merging.
> add a way to efficiently map many project options to FCS options at once

- global.json
- src/Ionide.ProjInfo/Library.fs
- test/Ionide.ProjInfo.Tests/Tests.fs
For some reason in 6.0.400, `CoreCompile` was not getting executed and theerfore we couldn't read the `FscCommandLineArgs`.  This adds `Clean` to the `designTimeBuildTargets`.
Hopefully addresses https://github.com/ionide/ionide-vscode-fsharp/issues/1748
> Fixing 6.0.400 issues

- .github/workflows/build.yml
This creates 3 'channels' of builds:
* what's in the repo global.json
* latest LTS SDK version
* latest SDK version, including prereleases
and builds and tests the library against those. This should give us heads-up when things start going bad in the future. This proves that 7.0 is broken currently, so I marked those builds as optional.
> Create multiple pipelines for .NET SDK testing in parallel

- src/Ionide.ProjInfo/Library.fs
- test/Ionide.ProjInfo.Tests/Tests.fs
The reason this is added is because it will force the BuildManager to pull the project files from disk per this comment: [https://github.com/dotnet/msbuild/blob/a3b647d766676a735211a42aa0726d1d940ed13d/src/Build/BackEnd/BuildManager/BuildManager.cs\#L2631-L2633](https://github.com/dotnet/msbuild/blob/a3b647d766676a735211a42aa0726d1d940ed13d/src/Build/BackEnd/BuildManager/BuildManager.cs#L2631-L2633)
> Adds ClearCachesAfterBuild to GraphBuildRequestData

- src/Ionide.ProjInfo/Library.fs
- src/Ionide.ProjInfo/Types.fs
- test/Ionide.ProjInfo.Tests/Tests.fs
This exposes the collected properties on `ProjectOptions`.  This will allow the caller to get at information like `IntermediateOutputPath` which can allow for consumers to stop hardcoding `obj` folder paths.
This can unblock: https://github.com/ionide/proj-info/issues/103 https://github.com/ionide/proj-info/issues/110
> Exposes Properties on ProjectOptions

- src/Ionide.ProjInfo.ProjectSystem/WorkspacePeek.fs
This PR will fix an exception occurring from unauthorized access of a sub-directory in ``scanDirs``
This will close #174 
I created a new function for error handling and returned empty arrays to keep the sequence expression in ``scanDirs`` relatively the same. I was unsure what to do when encountering an exception so I decided to add similar logging logic to what's already present in the repository.
I'm unsure how I would add tests for this.
Any feedback would be much appreciated!
(I forgot to create a new branch on my fork... sorry about that)
> Fix access error while reading project files.

- .config/dotnet-tools.json
- .vscode/settings.json
- CHANGELOG.md
- src/Ionide.ProjInfo.FCS/Library.fs
- src/Ionide.ProjInfo/Library.fs
- src/Ionide.ProjInfo/Types.fs
- test/Ionide.ProjInfo.Tests/TestAssets.fs
- test/Ionide.ProjInfo.Tests/Tests.fs
- test/examples/sample-netsdk-prodref/README.md
- test/examples/sample-netsdk-prodref/l1/Library.fs
- test/examples/sample-netsdk-prodref/l1/l1.fsproj
- test/examples/sample-netsdk-prodref/l2/Library.fs
- test/examples/sample-netsdk-prodref/l2/l2.fsproj
Adds support for reading and deferring to TargetRefPath when it exists. This property points to the reference assembly that matches the _implementation_ assembly that exists in `TargetPath`. There's a new member to help navigate the proper usage. When ref assemblies are present, the FSharpReferencedProject items returned as part of a generated FSharpProjectOptions object will use the ref assembly as the source of truth, not the implementation assembly.
> Add support for reference assemblies to ProjInfo

- src/Ionide.ProjInfo.ProjectSystem/Environment.fs
- src/Ionide.ProjInfo.Sln/FileUtilities.cs
- src/Ionide.ProjInfo.Sln/NativeMethods.cs
Per [the docs](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli#api-incompatibility) some APIs are unusable from a single-file deployment. This just removes uses of them from ProjInfo, which is easy because nothing was using any of these members anymore.
> Remove some uses of Assembly.Location and other methods

- .github/workflows/build.yml
- .vscode/launch.json
- src/Ionide.ProjInfo/Library.fs
- test/Ionide.ProjInfo.Tests/TestAssets.fs
- test/Ionide.ProjInfo.Tests/Tests.fs
- test/examples/missing-import/Program.fs
- test/examples/missing-import/missing-import.fsproj
Fixes #205.
This one got away from me a bit, but I think it's for the best.
To load project files with missing Imports, we need to supply one or two ProjectLoadSettings flags to everywhere a project file could be parsed. These flags are `ProjectLoadSettings.IgnoreMissingImports` and `ProjectLoadSettings.IgnoreInvalidImports`. Ideally we need to find everywhere that a project would be loaded (so anywhere `Project(...)` or `ProjectInstance(...)` occur) and make sure these flags are applied.
For our purposes there are two main places that `ProjectLoadSettings` can be specified
* when the `Project` constructor is called in the `WorkspaceLoader`
* as part of the `buildParameters` for the `WorkspaceLoaderViaProjectGraph`
Applying these changes to the existing call-sites was fairly easy - there …
> Allow loading of projects that are missing imports.

- src/Ionide.ProjInfo/Library.fs
- test/Ionide.ProjInfo.Tests/FileUtils.fs
- test/Ionide.ProjInfo.Tests/TestAssets.fs
- test/Ionide.ProjInfo.Tests/Tests.fs
- test/examples/traversal-project/dirs.proj
Traversal projects are a nice alternative to solutions, but they don't have great IDE support because they lack many of the targets/properties that 'normal' projects have. This PR introduces support for traversal projects basically by detecting them just enough to get their ProjectReferences, and then doing nothing else with them.
> Support traversal projects

- .gitignore
- src/Ionide.ProjInfo/Library.fs
This PR is because the message I got from Ionide was very cryptic when it was unable to parse the "you don't have a compatible .NET installed" message.
(I can't even build proj-info locally because I can't install Paket, because NuGet.org appears to be having an intermittent outage: `dotnet` thinks api.nuget.org doesn't exist even with `--no-cache`, and I just saw a pipeline fail to perform a NuGet install. Just another day in .NET.)
> Add clearer message on failure

- src/Ionide.ProjInfo/Library.fs
- src/Ionide.ProjInfo/Types.fs
- src/Ionide.ProjInfo/VisualTree.fs
I'm looking at writing something Myriad-like which also has access to the typed AST and other such compiler information, and it would really help if I could pick up configuration from the project file. Myriad itself [does this directly in MsBuild rules](https://github.com/MoiraeSoftware/myriad/blob/3c9818faabf9d508c10c28d5ecd26e66fafb48a1/src/Myriad.Sdk/build/Myriad.Sdk.targets#L96), but I would like to program in a language that is not MsBuild-flavoured XML, so I'd like to use proj-info to get the build graph and work out what I need to generate.
> Add CompileItem metadata to types

- src/Ionide.ProjInfo/InspectSln.fs
- test/Ionide.ProjInfo.Tests/TestAssets.fs
- test/Ionide.ProjInfo.Tests/Tests.fs
- test/examples/sample12-solution-filter-with-one-project/classlibf1/Library.fs
- test/examples/sample12-solution-filter-with-one-project/classlibf1/classlibf1.fsproj
- test/examples/sample12-solution-filter-with-one-project/classlibf2/Library.fs
- test/examples/sample12-solution-filter-with-one-project/classlibf2/classlibf2.fsproj
- test/examples/sample12-solution-filter-with-one-project/sample12-solution-filter-with-one-project.slnf
- test/examples/sample12-solution-filter-with-one-project/sample12-solution-with-two-projects.sln
refs https://github.com/ionide/ionide-vscode-fsharp/issues/1708
As mentioned in https://github.com/ionide/ionide-vscode-fsharp/issues/1708#issuecomment-2883426891, when I try to load a solution filter for one of my projects in Ionide 7.25.8 I don't get any projects loaded for the solution.
(I do get the guid entries described in https://github.com/ionide/ionide-vscode-fsharp/issues/2067, but that's a different issue).
So - I had a go at adding a new unit test for a solution / solution filter pair, and when I tried debugging that I found:
1) When it read the path to the solution file out of the filter file, it only got the file name of the parent solution rather than the path (the solution and filter are in the same directory). It then failed to load that solution.
So - try to fix that by …
> Tweaks to solution filter loading

- src/Ionide.ProjInfo/InspectSln.fs
refs https://github.com/ionide/proj-info/pull/233#discussion_r2094469723
The version prior to the solution library change was using the name of folders rather than the path - https://github.com/ionide/proj-info/blob/912538a84ea051c56a30cf5592216b5160fe6968/src/Ionide.ProjInfo/InspectSln.fs#L78 - and that seems to be what things higher up the stack are expecting for folders
> Set the Name property of folders to the display name instead of the path

- test/Ionide.ProjInfo.Tests/Tests.fs
One of the previpis 2 PRs added a new test that expected the folder name to include path separator characters, and then the other fixed it so that the folder names are just the names with no separators, so the two didn't get on with each other
> Fix the 'sample13 sln with solution files' test
